# Python


Q1. Consider a matrix whose cells are filled with 0’s and 1’s. If two 1’s are adjacent to each other,
they are said to be connected. A component is defined as a set of one or more 1’s that are
adjacent to each other. An adjacency can be of 5 types - horizontal, vertical, diagonal,
horizontal_vertical and horizontal_vertical_diagonal. Given a binary matrix, find the total
number of components for a given adjacency type.

In [ ]:
import numpy as np
  
Row = int(input())
Col = int(input())

# single line separated by space
entries = list(map(int, input().split()))
  
# For printing the matrix
matrix = np.array(entries).reshape(Row, Col)
print(matrix)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [ ]:
num_components = 0
for i in matrix:
    num_components += sum(i)
num_components

13

In [ ]:
# Horizontal adjacency
def num_horizontal(input, total_h1):
    for i in range(len(input)):
        for j in range(len(input[i])-1):
            if input[i][j] == 1:
                if input[i][j+1] == 1:
                    total_h1 -= 1
    return total_h1
h = num_horizontal(matrix, num_components)
h

11

In [ ]:
# Vertical adjacency
def vertical(input, tot_num):
    total_v1 = 0
    for i in range(len(input)):
        for j in range(len(input[i])-1):
            if input[j][i] == 1:
                if input[i][j+1] == 1:
                    total_v1 += 1
    return tot_num-total_v1
v = vertical(matrix, num_components)
v

9

In [ ]:
# Diagonal adjacency
def diagonal(input, tot_num):
    total_d1 = 0
    for i in range(len(input)):
        for j in range(len(input[i])-1):
            if input[i][i] == 1:
              if input[i-1][j-1] == 1:
                total_d1+= 1
    return tot_num-total_d1
d = diagonal(matrix, num_components)
d

3

In [ ]:
# Horizontal_Vertical adjacency
def num_hv(input, tot_num):
    total_hv1 = 0
    for i in range(len(input)):
        for j in range(len(input[i])-1):
            if input[i][j] == 1:
                if input[i][j+1] == 1:
                    total_hv1 += 1
            if input[j][i] == 1:
                if input[i][j+1] == 1:
                    total_hv1 += 1
    return tot_num-total_hv1
hv = num_hv(matrix, num_components)
hv

7

In [ ]:
# Horizontal_Vertical_Diagonal adjacency
def num_hvd(input):
    total_hvd1 = 0
    for i in range(len(input)):
        for j in range(len(input[i])-1):
            if input[i-1][j] == 1:
                if input[i-1][j-1] == 1:
                  if input[i-2][j]==1:
                    if input[i-2][j-1]==1:                                    
                        total_hvd1 += 1
    return total_hvd1
hvd = num_hvd(matrix)
hvd

1